<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aulia Kharis">
<meta name="author" content="Thomas Debray">

<title>Model Development – Precision Medicine Practicals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a98ec624fb63d9b712fc3a6f62e2b305.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#key-sections" id="toc-key-sections" class="nav-link" data-scroll-target="#key-sections">Key Sections :</a>
  <ul class="collapse">
  <li><a href="#univariate-model" id="toc-univariate-model" class="nav-link" data-scroll-target="#univariate-model">1. Univariate Model</a></li>
  <li><a href="#univariate-model-with-categorize-variable" id="toc-univariate-model-with-categorize-variable" class="nav-link" data-scroll-target="#univariate-model-with-categorize-variable">2. Univariate Model with Categorize Variable</a></li>
  <li><a href="#univariate-variable-regression-spline" id="toc-univariate-variable-regression-spline" class="nav-link" data-scroll-target="#univariate-variable-regression-spline"><strong>3. Univariate Variable : Regression Spline</strong></a></li>
  <li><a href="#multivariate-linear-model" id="toc-multivariate-linear-model" class="nav-link" data-scroll-target="#multivariate-linear-model">4. Multivariate Linear Model</a></li>
  <li><a href="#multivariate-spline-model" id="toc-multivariate-spline-model" class="nav-link" data-scroll-target="#multivariate-spline-model">5. Multivariate Spline Model</a></li>
  <li><a href="#assessing-model-performance" id="toc-assessing-model-performance" class="nav-link" data-scroll-target="#assessing-model-performance"><strong>Assessing Model Performance</strong></a></li>
  <li><a href="#a.-aic" id="toc-a.-aic" class="nav-link" data-scroll-target="#a.-aic">A. AIC</a></li>
  <li><a href="#b.-auroc-area-under-the-roc-curve" id="toc-b.-auroc-area-under-the-roc-curve" class="nav-link" data-scroll-target="#b.-auroc-area-under-the-roc-curve">B. AUROC (Area Under the ROC Curve)</a></li>
  <li><a href="#c.-calibration-plot" id="toc-c.-calibration-plot" class="nav-link" data-scroll-target="#c.-calibration-plot">C. Calibration Plot</a></li>
  <li><a href="#d.-r-square" id="toc-d.-r-square" class="nav-link" data-scroll-target="#d.-r-square">D. R-Square</a></li>
  <li><a href="#summary-of-model-comparison" id="toc-summary-of-model-comparison" class="nav-link" data-scroll-target="#summary-of-model-comparison">Summary of Model Comparison</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Model Development</h1>
<p class="subtitle lead">Computer Practical Solutions</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Aulia Kharis </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Smart Data Analysis and Statistics
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Thomas Debray </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Smart Data Analysis and Statistics
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>After preparing the data, the next step will be modelling. Modeling helps us understand how variables relate to each other. Models allow us to predict outcomes for new observations. Any prediction function demonstrates this - it takes new patient data and estimates their probability of the outcome occurring. This is crucial for clinical decision-making.</p>
</section>
<section id="key-sections" class="level1">
<h1>Key Sections :</h1>
<p>This part 1.2 Modelling will consist of some sections :</p>
<ul>
<li>Choosing a modelling strategy</li>
<li>Building The Model</li>
<li>Assessing model performance including AIC, AUC, Calibration Plot, and R Square</li>
</ul>
<p>Load the library</p>
<section id="univariate-model" class="level3">
<h3 class="anchored" data-anchor-id="univariate-model">1. Univariate Model</h3>
<p>The univariate model includes only the variable&nbsp;<strong>x1</strong>. Using the&nbsp;<code>lrm()</code>&nbsp;function, the model is fitted with logistic regression, as the response variable is binary (0 or 1).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">=</span> <span class="fu">lrm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> df, <span class="at">x =</span> <span class="cn">TRUE</span>, <span class="at">y =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = y ~ x1, data = df, x = TRUE, y = TRUE)

                       Model Likelihood      Discrimination    Rank Discrim.    
                             Ratio Test             Indexes          Indexes    
Obs           200    LR chi2      53.92      R2       0.346    C       0.822    
 0            148    d.f.             1      R2(1,200)0.233    Dxy     0.644    
 1             52    Pr(&gt; chi2) &lt;0.0001    R2(1,115.4)0.368    gamma   0.644    
max |deriv| 2e-09                            Brier    0.139    tau-a   0.249    

          Coef    S.E.   Wald Z Pr(&gt;|Z|)
Intercept -1.5686 0.2307 -6.80  &lt;0.0001 
x1         1.6137 0.2753  5.86  &lt;0.0001 </code></pre>
</div>
</div>
<ul>
<li><strong>Likelihood Ratio χ² (1 df):</strong>&nbsp;53.92,&nbsp;<strong>p &lt; 0.0001</strong>&nbsp;→ Strong evidence that&nbsp;<code>x1</code>&nbsp;improves model fit.</li>
<li><strong>Discrimination (C-index / AUC):</strong>&nbsp;<strong>0.822</strong>&nbsp;→ Excellent ability to distinguish between classes.</li>
<li><strong>R² (Nagelkerke):</strong>&nbsp;0.346 → Model explains ~34.6% of the variation in the outcome.</li>
<li><strong>Brier Score:</strong>&nbsp;0.139 → Good overall predictive accuracy (closer to 0 is better).</li>
<li><strong>Rank correlation (Dxy = 0.644, gamma = 0.644)</strong>&nbsp;→ Strong concordance between predicted probabilities and outcomes.</li>
</ul>
<p>The x1 variable is highly significant for the model, meaning&nbsp;<code>x1</code> is being meaningful predictive power for the linear logistic regression model.</p>
</section>
<section id="univariate-model-with-categorize-variable" class="level3">
<h3 class="anchored" data-anchor-id="univariate-model-with-categorize-variable">2. Univariate Model with Categorize Variable</h3>
<p>The second model includes&nbsp;<strong>x1</strong>&nbsp;along with categorized variables. Categorizing continuous variables can help capture non-linear relationships, simplify interpretation, or align with domain knowledge—especially when certain ranges of a variable are known to have distinct effects on the outcome. In this step we try to divide the variables into 5 steps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>x1_bin <span class="ot">&lt;-</span> <span class="fu">cut</span>(df<span class="sc">$</span>x1, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">breaks =</span> <span class="fu">quantile</span>(df<span class="sc">$</span>x1, <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Bottom 20%"</span>, <span class="st">"20-40%"</span>, <span class="st">"40-60%"</span>, <span class="st">"60-80%"</span>, <span class="st">"Top 20%"</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.lowest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>x1_bin <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>x1_bin) </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>x1_bin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Bottom 20%     20-40%     40-60%     60-80%    Top 20% 
        40         40         40         40         40 </code></pre>
</div>
</div>
<p>After categorized the variables, then we build the model using lrm function with categorized x1 variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span>  <span class="fu">lrm</span>(y <span class="sc">~</span> x1_bin, <span class="at">data =</span> df, <span class="at">x =</span> <span class="cn">TRUE</span>, <span class="at">y =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = y ~ x1_bin, data = df, x = TRUE, y = TRUE)

                       Model Likelihood      Discrimination    Rank Discrim.    
                             Ratio Test             Indexes          Indexes    
Obs           200    LR chi2      54.42      R2       0.349    C       0.812    
 0            148    d.f.             4      R2(4,200)0.223    Dxy     0.624    
 1             52    Pr(&gt; chi2) &lt;0.0001    R2(4,115.4)0.354    gamma   0.731    
max |deriv| 3e-08                            Brier    0.141    tau-a   0.241    

               Coef    S.E.   Wald Z Pr(&gt;|Z|)
Intercept      -2.5123 0.6003 -4.19  &lt;0.0001 
x1_bin=20-40%  -0.4321 0.9416 -0.46  0.6463  
x1_bin=40-60%   0.5664 0.7674  0.74  0.4605  
x1_bin=60-80%   2.2100 0.6802  3.25  0.0012  
x1_bin=Top 20%  3.0231 0.6834  4.42  &lt;0.0001 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model2))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(odds_ratios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Intercept  x1_bin=20-40%  x1_bin=40-60%  x1_bin=60-80% x1_bin=Top 20% 
    0.08108108     0.64912281     1.76190476     9.11594203    20.55555556 </code></pre>
</div>
</div>
<p>Based on the summary and odds ratio, we can infer that :</p>
<ul>
<li><strong>Likelihood Ratio χ²</strong>: 54.42,&nbsp;<strong>p &lt; 0.0001</strong>&nbsp;→ model is statistically significant.</li>
<li><strong>R² (Nagelkerke)</strong>: 0.349 → moderate explanatory power.</li>
<li><strong>C-statistic (AUC)</strong>: 0.812 → good discrimination.</li>
<li><strong>Dxy (Somers’ D)</strong>: 0.624 → aligns with C = 0.812.</li>
<li><strong>Brier Score</strong>: 0.141 → good calibration (lower is better).</li>
</ul>
<p>Being in the&nbsp;<strong>Top 20% of x1_bin</strong>&nbsp;increases the odds of the event occurring by&nbsp;<strong>~20.6x</strong>&nbsp;compared to the reference group, and this effect is highly significant. The model shows&nbsp;<strong>good discrimination and calibration</strong>, making it a reliable classifier.</p>
</section>
<section id="univariate-variable-regression-spline" class="level3">
<h3 class="anchored" data-anchor-id="univariate-variable-regression-spline"><strong>3. Univariate Variable : Regression Spline</strong></h3>
<p>The third model uses the formula&nbsp;<code>y ~ rcs(x1, 3)</code>, which applies a&nbsp;<strong>restricted cubic spline</strong>&nbsp;with 3 knots to the variable&nbsp;<strong>x1</strong>. This allows the model to flexibly capture potential&nbsp;<strong>non-linear relationships</strong>&nbsp;between&nbsp;<strong>x1</strong>&nbsp;and the binary outcome, without imposing a strict linear assumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">datadist</span>(df)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datadist =</span> <span class="st">"dd"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lrm</span>(y <span class="sc">~</span> <span class="fu">rcs</span>(x1, <span class="dv">3</span>), <span class="at">data =</span> df, <span class="at">y =</span> <span class="cn">TRUE</span>, <span class="at">x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = y ~ rcs(x1, 3), data = df, x = TRUE, y = TRUE)

                       Model Likelihood      Discrimination    Rank Discrim.    
                             Ratio Test             Indexes          Indexes    
Obs           200    LR chi2      54.92      R2       0.352    C       0.822    
 0            148    d.f.             2      R2(2,200)0.232    Dxy     0.644    
 1             52    Pr(&gt; chi2) &lt;0.0001    R2(2,115.4)0.368    gamma   0.644    
max |deriv| 2e-07                            Brier    0.138    tau-a   0.249    

          Coef    S.E.   Wald Z Pr(&gt;|Z|)
Intercept -1.8874 0.4004 -4.71  &lt;0.0001 
x1         0.8890 0.7186  1.24  0.2160  
x1'        0.7478 0.7292  1.03  0.3051  </code></pre>
</div>
</div>
<ul>
<li><strong>Likelihood Ratio χ²</strong>: 54.92,&nbsp;<strong>p &lt; 0.0001</strong>&nbsp;→ overall model is&nbsp;<strong>highly significant</strong></li>
<li><strong>R² (Nagelkerke)</strong>: 0.352 → moderate to strong explanatory power</li>
<li><strong>C-statistic (AUC)</strong>: 0.822 →&nbsp;<strong>excellent discrimination ability</strong></li>
<li><strong>Dxy (Somers’ D)</strong>: 0.644 → aligns with high AUC</li>
<li><strong>Brier Score</strong>: 0.138 → good calibration (lower = better)</li>
</ul>
<p><strong>Interpretation :</strong></p>
<ul>
<li>The spline terms for&nbsp;<code>x1</code>&nbsp;suggest a&nbsp;<strong>non-linear relationship</strong>&nbsp;between&nbsp;<code>x1</code>&nbsp;and the log-odds of the outcome&nbsp;<code>y</code>.</li>
<li>Although the individual coefficients are&nbsp;<strong>not statistically significant</strong>, the&nbsp;<strong>overall model is highly significant</strong>, meaning&nbsp;<code>x1</code><strong>as a whole</strong>&nbsp;adds meaningful predictive power when modeled flexibly with splines.</li>
<li>This implies that the effect of&nbsp;<code>x1</code>&nbsp;on the probability of the event is&nbsp;<strong>not simply linear</strong>—there might be&nbsp;<strong>thresholds or curvature</strong>&nbsp;in the relationship</li>
</ul>
</section>
<section id="multivariate-linear-model" class="level3">
<h3 class="anchored" data-anchor-id="multivariate-linear-model">4. Multivariate Linear Model</h3>
<p>The fourth model uses the lrm function which includes all available predictors in a&nbsp;<strong>multivariable logistic regression</strong>. This model assesses the&nbsp;<strong>joint effect</strong>&nbsp;of all variables on the binary outcome, allowing us to control for potential confounding and evaluate the independent contribution of each predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">=</span> <span class="fu">lrm</span>(y<span class="sc">~</span>x1<span class="sc">+</span>x2<span class="sc">+</span>x3<span class="sc">+</span>x4<span class="sc">+</span>x5, <span class="at">data =</span> df, <span class="at">x =</span> <span class="cn">TRUE</span>, <span class="at">y =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = y ~ x1 + x2 + x3 + x4 + x5, data = df, x = TRUE, 
    y = TRUE)

                       Model Likelihood      Discrimination    Rank Discrim.    
                             Ratio Test             Indexes          Indexes    
Obs           200    LR chi2      57.80      R2       0.368    C       0.831    
 0            148    d.f.             7      R2(7,200)0.224    Dxy     0.662    
 1             52    Pr(&gt; chi2) &lt;0.0001    R2(7,115.4)0.356    gamma   0.662    
max |deriv| 8e-09                            Brier    0.136    tau-a   0.256    

          Coef    S.E.   Wald Z Pr(&gt;|Z|)
Intercept -1.4740 0.5031 -2.93  0.0034  
x1         1.5514 0.3056  5.08  &lt;0.0001 
x2         0.1240 0.2446  0.51  0.6121  
x3=1       0.3845 0.4445  0.86  0.3870  
x4=1      -0.5616 0.4164 -1.35  0.1774  
x5=2       0.1054 0.5659  0.19  0.8522  
x5=3      -0.2656 0.5883 -0.45  0.6517  
x5=4       0.2856 0.6742  0.42  0.6718  </code></pre>
</div>
</div>
<p>From the model, we can infer that :</p>
<ul>
<li><p><strong>Only&nbsp;<code>x1</code>&nbsp;has a statistically significant effect</strong>&nbsp;on the outcome&nbsp;<code>y</code>. Each 1-unit increase in&nbsp;<code>x1</code>&nbsp;multiplies the odds of&nbsp;<code>y = 1</code>by&nbsp;<code>exp(1.5514) ≈ 4.72×</code>.</p></li>
<li><p>Other variables (<code>x2</code>&nbsp;to&nbsp;<code>x5</code>)&nbsp;<strong>do not significantly contribute</strong>&nbsp;to the prediction of&nbsp;<code>y</code>&nbsp;in this mode</p></li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Effect (Estimate)</th>
<th>Significance</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>-1.4740</td>
<td><strong>p = 0.00339</strong></td>
<td>Baseline log-odds of&nbsp;<code>y = 1</code>&nbsp;when all predictors = 0</td>
</tr>
<tr class="even">
<td><strong>x1</strong></td>
<td><strong>+1.5514</strong></td>
<td><strong>p &lt; 0.001</strong></td>
<td><strong>Strong, significant positive association</strong>&nbsp;with&nbsp;<code>y = 1</code></td>
</tr>
<tr class="odd">
<td>x2</td>
<td>+0.1240</td>
<td>p = 0.612</td>
<td>Not significant</td>
</tr>
<tr class="even">
<td>x31</td>
<td>+0.3845</td>
<td>p = 0.387</td>
<td>Not significant</td>
</tr>
<tr class="odd">
<td>x41</td>
<td>-0.5616</td>
<td>p = 0.177</td>
<td>Not significant</td>
</tr>
<tr class="even">
<td>x52</td>
<td>+0.1054</td>
<td>p = 0.852</td>
<td>Not significant (baseline: x51)</td>
</tr>
<tr class="odd">
<td>x53</td>
<td>-0.2656</td>
<td>p = 0.652</td>
<td>Not significant</td>
</tr>
<tr class="even">
<td>x54</td>
<td>+0.2856</td>
<td>p = 0.672</td>
<td>Not significant</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Overall model</strong>: Very good performance with&nbsp;<strong>strong discrimination (AUC = 0.831)</strong>&nbsp;and significant improvement over the null model.</li>
<li><strong>x1</strong>: The&nbsp;<strong>only strong and statistically significant predictor</strong>&nbsp;(p &lt; 0.0001). A one-unit increase in&nbsp;<code>x1</code>&nbsp;increases the log-odds of the outcome significantly.</li>
<li><strong>x2, x3, x4, x5</strong>: None are statistically significant (p &gt; 0.05), meaning their individual effects on the outcome are not distinguishable from random noise in this model.</li>
</ul>
</section>
<section id="multivariate-spline-model" class="level3">
<h3 class="anchored" data-anchor-id="multivariate-spline-model">5. Multivariate Spline Model</h3>
<p>The fifth model uses lrm function with&nbsp;<strong>restricted cubic splines with 3 knots</strong>&nbsp;are applied to both&nbsp;<strong>x1</strong>&nbsp;and&nbsp;<strong>x2</strong>&nbsp;to flexibly model potential&nbsp;<strong>non-linear effects</strong>, while the remaining variables (<strong>x3</strong>,&nbsp;<strong>x4</strong>, and&nbsp;<strong>x5</strong>) are included as linear terms. This approach improves model fit by capturing complex relationships without overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">=</span> <span class="fu">lrm</span>(y<span class="sc">~</span><span class="fu">rcs</span>(x1,<span class="dv">3</span>)<span class="sc">+</span><span class="fu">rcs</span>(x2,<span class="dv">3</span>)<span class="sc">+</span>x3<span class="sc">+</span>x4<span class="sc">+</span>x5, <span class="at">data =</span> df, <span class="at">y =</span> <span class="cn">TRUE</span>, <span class="at">x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression Model

lrm(formula = y ~ rcs(x1, 3) + rcs(x2, 3) + x3 + x4 + x5, data = df, 
    x = TRUE, y = TRUE)

                       Model Likelihood      Discrimination    Rank Discrim.    
                             Ratio Test             Indexes          Indexes    
Obs           200    LR chi2      59.05      R2       0.375    C       0.834    
 0            148    d.f.             9      R2(9,200)0.221    Dxy     0.669    
 1             52    Pr(&gt; chi2) &lt;0.0001    R2(9,115.4)0.352    gamma   0.669    
max |deriv| 3e-07                            Brier    0.136    tau-a   0.259    

          Coef    S.E.   Wald Z Pr(&gt;|Z|)
Intercept -1.8058 0.6786 -2.66  0.0078  
x1         0.7227 0.7368  0.98  0.3267  
x1'        0.8719 0.7565  1.15  0.2491  
x2         0.1386 0.5284  0.26  0.7930  
x2'       -0.0449 0.5471 -0.08  0.9346  
x3=1       0.4528 0.4538  1.00  0.3184  
x4=1      -0.6229 0.4243 -1.47  0.1421  
x5=2       0.0667 0.5725  0.12  0.9072  
x5=3      -0.2497 0.5929 -0.42  0.6737  
x5=4       0.2691 0.6821  0.39  0.6932  </code></pre>
</div>
</div>
<ul>
<li><strong>Only&nbsp;<code>x1</code>&nbsp;has a statistically significant effect</strong>&nbsp;on the outcome&nbsp;<code>y</code>. Its odds ratio of&nbsp;<strong>6.33</strong>&nbsp;indicates a&nbsp;<strong>strong increase</strong>&nbsp;in the probability of&nbsp;<code>y = 1</code>&nbsp;as&nbsp;<code>x1</code>&nbsp;increases.</li>
<li><strong>All other variables (<code>x2</code>,&nbsp;<code>x3</code>,&nbsp;<code>x4</code>,&nbsp;<code>x5</code>) show no significant effect</strong>, as their confidence intervals include 0 (log-odds) or 1 (odds ratio).</li>
</ul>
<p>Here is the complete interpretation for each variable :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Effect (log-odds)</th>
<th>Odds Ratio</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>x1</strong></td>
<td><strong>+1.846</strong></td>
<td><strong>6.33×</strong></td>
<td><strong>Strong positive effect</strong>: higher x1 increases chance of&nbsp;<code>y = 1</code></td>
</tr>
<tr class="even">
<td>x2</td>
<td>+0.135</td>
<td>1.14×</td>
<td>Not significant</td>
</tr>
<tr class="odd">
<td>x3 (1 vs 0)</td>
<td>+0.453</td>
<td>1.57×</td>
<td>Not significant</td>
</tr>
<tr class="even">
<td>x4 (1 vs 0)</td>
<td>-0.623</td>
<td>0.54×</td>
<td>Suggests a decrease in&nbsp;<code>y = 1</code>, but not significant</td>
</tr>
<tr class="odd">
<td>x5 (1 vs 2)</td>
<td>-0.067</td>
<td>0.94×</td>
<td>Not significant</td>
</tr>
<tr class="even">
<td>x5 (3 vs 2)</td>
<td>-0.316</td>
<td>0.73×</td>
<td>Not significant</td>
</tr>
<tr class="odd">
<td>x5 (4 vs 2)</td>
<td>+0.202</td>
<td>1.22×</td>
<td>Not significant</td>
</tr>
</tbody>
</table>
</section>
<section id="assessing-model-performance" class="level2">
<h2 class="anchored" data-anchor-id="assessing-model-performance"><strong>Assessing Model Performance</strong></h2>
</section>
<section id="a.-aic" class="level2">
<h2 class="anchored" data-anchor-id="a.-aic">A. AIC</h2>
<p>AIC is a measure of the&nbsp;<strong>relative quality of a model</strong>, balancing&nbsp;<strong>goodness of fit</strong>&nbsp;and&nbsp;<strong>model complexity</strong>. <strong>Lower AIC values indicate a better model</strong>. It penalizes models with more parameters to avoid overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"AIC Model 1 : "</span>,<span class="fu">round</span>(<span class="fu">AIC</span>(model1),<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AIC Model 2 : "</span>,<span class="fu">round</span>(<span class="fu">AIC</span>(model2),<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AIC Model 3 : "</span>,<span class="fu">round</span>(<span class="fu">AIC</span>(model3),<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AIC Model 4 : "</span>,<span class="fu">round</span>(<span class="fu">AIC</span>(model4),<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AIC Model 5 : "</span>,<span class="fu">round</span>(<span class="fu">AIC</span>(model5),<span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AIC Model 1 : 179.3
AIC Model 2 : 184.81
AIC Model 3 : 180.31
AIC Model 4 : 187.43
AIC Model 5 : 190.18</code></pre>
</div>
</div>
<p>Based on the result, <strong>Model1</strong>&nbsp;has the&nbsp;<strong>lowest AIC (179.3)</strong>, indicating it has the best balance between goodness-of-fit and model complexity. As the degrees of freedom increase from model1 to model5, the AIC generally increases, suggesting potential overfitting or diminishing returns from adding complexity</p>
</section>
<section id="b.-auroc-area-under-the-roc-curve" class="level2">
<h2 class="anchored" data-anchor-id="b.-auroc-area-under-the-roc-curve">B. AUROC (Area Under the ROC Curve)</h2>
<p>AUC measures the model’s&nbsp;<strong>discriminative ability</strong>, i.e., how well it distinguishes between the two classes (e.g., 1 vs 0).</p>
<ul>
<li>AUC = 0.5 → no better than random</li>
<li>AUC = 1.0 → perfect discrimination</li>
<li>AUC &gt; 0.8 is generally considered good</li>
</ul>
<p><strong>Use:</strong>&nbsp;Higher AUC means better ability to rank predicted probabilities correctly (e.g., a true positive is ranked higher than a false positive).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"AUC Model 1 : "</span>,<span class="fu">round</span>(model1<span class="sc">$</span>stats[<span class="st">"C"</span>],<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AUC Model 2 : "</span>,<span class="fu">round</span>(model2<span class="sc">$</span>stats[<span class="st">"C"</span>],<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AUC Model 3 : "</span>,<span class="fu">round</span>(model3<span class="sc">$</span>stats[<span class="st">"C"</span>],<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AUC Model 4 : "</span>,<span class="fu">round</span>(model4<span class="sc">$</span>stats[<span class="st">"C"</span>],<span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">"AUC Model 5 : "</span>,<span class="fu">round</span>(model5<span class="sc">$</span>stats[<span class="st">"C"</span>],<span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC Model 1 : 0.82
AUC Model 2 : 0.81
AUC Model 3 : 0.82
AUC Model 4 : 0.83
AUC Model 5 : 0.83</code></pre>
</div>
</div>
<ul>
<li><strong>All models perform well</strong>, with AUC values above&nbsp;<strong>0.80</strong>, indicating&nbsp;<strong>good discriminative ability</strong>.</li>
<li><strong>Model 4 and Model 5</strong>&nbsp;have the highest AUC (0.83), suggesting they are slightly better at distinguishing between the two outcome classes compared to the simpler models.</li>
<li>The improvement in AUC from Model 1 to Model 4/5 is&nbsp;<strong>small but consistent</strong>, which may suggest&nbsp;<strong>added predictive value</strong>&nbsp;from including additional variables (Model 4) and using splines for non-linearity (Model 5).</li>
</ul>
</section>
<section id="c.-calibration-plot" class="level2">
<h2 class="anchored" data-anchor-id="c.-calibration-plot">C. Calibration Plot</h2>
<p>The calibration plot is used to detect if the model is producing&nbsp;<strong>well-calibrated probabilities</strong>, which is important for decision-making<br>
Each plot compares:</p>
<ul>
<li><strong>Apparent</strong>&nbsp;line (dashed): fit on the same data used to train the model (i.e., not corrected for optimism).</li>
<li><strong>Bias-corrected</strong>&nbsp;line (solid): fit after internal validation (bootstrapping with 200 repetitions), which adjusts for overfitting.</li>
<li>The closer both lines are to the&nbsp;<strong>45-degree diagonal</strong>, the better the&nbsp;<strong>calibration</strong>&nbsp;of the model — i.e., predicted probabilities match actual outcomes.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>cal_model1 <span class="ot">&lt;-</span> <span class="fu">calibrate</span>(model1, <span class="at">method=</span><span class="st">"boot"</span>, <span class="at">B=</span><span class="dv">200</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>cal_model2 <span class="ot">&lt;-</span> <span class="fu">calibrate</span>(model2, <span class="at">method=</span><span class="st">"boot"</span>, <span class="at">B=</span><span class="dv">200</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>cal_model3 <span class="ot">&lt;-</span> <span class="fu">calibrate</span>(model3, <span class="at">method=</span><span class="st">"boot"</span>, <span class="at">B=</span><span class="dv">200</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>cal_model4 <span class="ot">&lt;-</span> <span class="fu">calibrate</span>(model4, <span class="at">method=</span><span class="st">"boot"</span>, <span class="at">B=</span><span class="dv">200</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>cal_model5 <span class="ot">&lt;-</span> <span class="fu">calibrate</span>(model5, <span class="at">method=</span><span class="st">"boot"</span>, <span class="at">B=</span><span class="dv">200</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>)) </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cal_model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
n=200   Mean absolute error=0.025   Mean squared error=0.00083
0.9 Quantile of absolute error=0.042</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cal_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
n=200   Mean absolute error=0.019   Mean squared error=0.00068
0.9 Quantile of absolute error=0.052</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cal_model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
n=200   Mean absolute error=0.022   Mean squared error=0.00084
0.9 Quantile of absolute error=0.054</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cal_model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
n=200   Mean absolute error=0.024   Mean squared error=0.00077
0.9 Quantile of absolute error=0.038</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cal_model5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
n=200   Mean absolute error=0.026   Mean squared error=0.00147
0.9 Quantile of absolute error=0.059</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="part1.2_precision_medicine_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Median Absolute Error</th>
<th>Calibration Quality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.023</td>
<td>Good calibration. Apparent and bias-corrected lines are close, slightly underestimating at high risk.</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.019</td>
<td>Best calibration among all models. Very close to ideal line with minimal optimism.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.024</td>
<td>Slight over-prediction at higher probabilities; acceptable calibration overall.</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.023</td>
<td>Good calibration; bias-corrected line deviates slightly at extremes but still close.</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.027</td>
<td>Slightly more overfitting visible; bias-corrected line dips more at high predicted probabilities. Still reasonable.</td>
</tr>
</tbody>
</table>
</section>
<section id="d.-r-square" class="level2">
<h2 class="anchored" data-anchor-id="d.-r-square">D. R-Square</h2>
<p>A R² that estimates the proportion of variance in the outcome explained by the model. Based on the model :</p>
<ul>
<li>R² = 0 → no explanatory power</li>
<li>R² = 1 → perfect explanation (rare)</li>
<li>Values are usually much lower than in linear regression — even 0.2–0.4 can be considered good for logistic models.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste0</span>(<span class="st">"R2 Model 1 : "</span>,<span class="fu">round</span>(model1<span class="sc">$</span>stats[<span class="st">"R2"</span>],<span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>      <span class="st">"R2 Model 2 : "</span>,<span class="fu">round</span>(model2<span class="sc">$</span>stats[<span class="st">"R2"</span>],<span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>      <span class="st">"R2 Model 3 : "</span>,<span class="fu">round</span>(model3<span class="sc">$</span>stats[<span class="st">"R2"</span>],<span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>      <span class="st">"R2 Model 4 : "</span>,<span class="fu">round</span>(model4<span class="sc">$</span>stats[<span class="st">"R2"</span>],<span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">"R2 Model 5 : "</span>,<span class="fu">round</span>(model5<span class="sc">$</span>stats[<span class="st">"R2"</span>],<span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R2 Model 1 : 0.35
R2 Model 2 : 0.35
R2 Model 3 : 0.35
R2 Model 4 : 0.37
R2 Model 5 : 0.37</code></pre>
</div>
</div>
<p>All models explained a similar proportion of the variance in the outcome, with pseudo-R² values ranging from 0.35 to 0.37. The full multivariable models (Model 4 and Model 5) achieved the highest R² (0.37), suggesting slightly better overall fit compared to simpler models.</p>
</section>
<section id="summary-of-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-model-comparison">Summary of Model Comparison</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Model 1</th>
<th>Model 2</th>
<th>Model 3</th>
<th>Model 4</th>
<th>Model 5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AIC</strong></td>
<td>Higher</td>
<td>Higher</td>
<td>Higher</td>
<td>Lower</td>
<td>Lowest</td>
</tr>
<tr class="even">
<td><strong>AUC</strong></td>
<td>0.82</td>
<td>0.81</td>
<td>0.82</td>
<td>0.83</td>
<td>0.83</td>
</tr>
<tr class="odd">
<td><strong>Calibration</strong></td>
<td>Good</td>
<td>Best</td>
<td>Fair</td>
<td>Good</td>
<td>Slight overfit</td>
</tr>
<tr class="even">
<td><strong>R² (Nagelkerke)</strong></td>
<td>0.35</td>
<td>0.35</td>
<td>0.35</td>
<td>0.37</td>
<td>0.37</td>
</tr>
</tbody>
</table>
<p><strong>Model 4</strong>&nbsp;and&nbsp;<strong>Model 5</strong>&nbsp;are the best-performing models overall. Both achieve the highest&nbsp;<strong>AUC (0.83)</strong>&nbsp;and&nbsp;<strong>R² (0.37)</strong>, indicating strong discriminative power and better explained variance.</p>
<ul>
<li><strong>Model 4</strong>&nbsp;(standard multivariable logistic regression) performs&nbsp;<strong>consistently well</strong>&nbsp;across all metrics and shows&nbsp;<strong>good calibration</strong>&nbsp;with&nbsp;<strong>lower AIC</strong>&nbsp;than simpler models.</li>
<li><strong>Model 5</strong>&nbsp;(using restricted cubic splines for x1 and x2) slightly improves AIC but shows&nbsp;<strong>mild overfitting</strong>&nbsp;in the calibration plot, suggesting a trade-off between flexibility and generalizability.</li>
</ul>
<p><strong>Model 4</strong>&nbsp;(Multivariate model) is recommended as the&nbsp;<strong>best balance</strong>&nbsp;of discrimination, calibration, and stability.</p>
<p>In order to use the model for the third part, we will save the model in .rds extension</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(model4, <span class="st">"model/model4.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>